name: Lint Awesome List
on:
  push:
  pull_request:
  schedule:
    # Run linter every week to catch regressions from external dependencies.
    - cron: 17 9 * * 1

jobs:

  updateTOC:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v2
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_PATHS: readme.md

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          # Fetch all history to please linter's age checks.
          fetch-depth: 0
      - uses: max/awesome-lint@master
